# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Proceed do backend directory
      run: cd ./room-panel-backend
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Download gradle
      run: ./gradlew wrapper
    - name: Test with Gradle
      run: ./gradlew clean test
    - name: Build with Gradle
      run: ./gradlew clean build
